# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20161021_1819'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.ManyToManyField(related_name='guests', to='login_reg.User')),
                ('planner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='login_reg.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
