# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20161021_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
