# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20161021_1819'),
        ('travels', '0004_auto_20161021_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='guest_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='trip_id',
            field=models.ManyToManyField(to='travels.Trip'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user_id',
            field=models.ManyToManyField(to='login_reg.User'),
        ),
    ]
